# Generated by Django 3.0.7 on 2022-06-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_studentresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='students',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='students',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='students',
            name='session_year_id',
        ),
        migrations.AddField(
            model_name='students',
            name='admission_location',
            field=models.CharField(default='UNKNOWN', max_length=50),
        ),
        migrations.AddField(
            model_name='students',
            name='admission_type',
            field=models.CharField(default='UNKNOWN', max_length=50),
        ),
        migrations.AddField(
            model_name='students',
            name='admittime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='deathtime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='diagnosis',
            field=models.TextField(default='UNKNOWN'),
        ),
        migrations.AddField(
            model_name='students',
            name='dischtime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='hadm_id',
            field=models.TextField(default='UNKNOWN'),
        ),
        migrations.AddField(
            model_name='students',
            name='insurance',
            field=models.CharField(default='UNKNOWN', max_length=50),
        ),
        migrations.AddField(
            model_name='students',
            name='marital_status',
            field=models.CharField(default='UNKNOWN', max_length=50),
        ),
        migrations.AddField(
            model_name='students',
            name='name',
            field=models.TextField(default='UNKNOWN'),
        ),
        migrations.AddField(
            model_name='students',
            name='subject_id',
            field=models.TextField(default='UNKNOWN'),
        ),
    ]
