# Generated by Django 3.0.7 on 2022-06-26 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course_name',
        ),
        migrations.AddField(
            model_name='courses',
            name='description',
            field=models.TextField(default='UNKNOWN'),
        ),
        migrations.AddField(
            model_name='courses',
            name='drg_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courses',
            name='drg_type',
            field=models.TextField(default='UNKNOWN'),
        ),
        migrations.AddField(
            model_name='courses',
            name='hadm_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='management_app.Admission'),
        ),
        migrations.AddField(
            model_name='courses',
            name='subject_id',
            field=models.TextField(default='UNKNOWN'),
        ),
    ]
