# Generated by Django 3.0.7 on 2022-07-03 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0002_auto_20220626_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='course_id',
            new_name='drug_id',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='staff_id',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='subject_name',
        ),
        migrations.AddField(
            model_name='subjects',
            name='hadm_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management_app.Admission'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='prescription_name',
            field=models.CharField(default='UNKNOWN', max_length=255),
        ),
    ]
